# Generated by Django 3.0.6 on 2020-12-21 06:37

import apps.home.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=150)),
                ('menu_url', models.CharField(max_length=250, unique=True)),
                ('menu_priority', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('menu_logo', models.ImageField(upload_to=apps.home.models.wrapper)),
            ],
        ),
        migrations.CreateModel(
            name='HomeMenuPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.IntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.HomeMenu')),
            ],
            options={
                'unique_together': {('member_type', 'menu')},
            },
        ),
    ]
