# Generated by Django 3.0.6 on 2020-12-21 06:37

import apps.common.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('map_location', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(upload_to=apps.common.upload.wrapper_center_logo)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
